compute_environment: LOCAL_MACHINE
distributed_type: DEEPSPEED
deepspeed_config:
 deepspeed_config_file: scripts/accelerate_configs/zero3.json
 zero3_init_flag: true
fsdp_config: {}
machine_rank: 0
main_process_ip: null
main_process_port: 29501
main_training_function: main
num_machines: 1
num_processes: 8
gpu_ids: 0,1,2,3,4,5,6,7
use_cpu: false